using System.ComponentModel.DataAnnotations.Schema;
namespace AuthenticationService.Models
{
    public class User
    {    
        /* This class shouls have two properties UserId and Password . 
         * UserId should not be auto generated and use None option to prevents 
         * the values from being generated by the database automatically.
         * The Password property returns string value.
         */
    }
}
